config/routes.rb
Rails.application.routes.draw do
	root to: 'users#new'

	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	resources :articles, only: %i[show index new create edit update destroy]
	resources :users, except: %i[new]
	resources :categories, except: %i[destroy]
	get 'signup', to: 'users#new'
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 6, maximum: 100 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :name,
	          presence: true,
	          uniqueness: true,
	          length: {
			maximum: 25,
			minimum: 3
	          }
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :articles, dependent: :destroy

	validates :username,
	          presence: true,
	          uniqueness: {
			case_sensitive: false
	          },
	          length: {
			minimum: 3,
			maximum: 25
	          }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email,
	          presence: true,
	          uniqueness: true,
	          length: {
			minimun: 10,
			maximum: 155
	          },
	          format: {
			with: VALID_EMAIL_REGEX
	          }

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to login_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: %i[show edit update destroy]
	before_action :require_user, except: %i[index show]
	before_action :require_same_user, only: %i[edit update destroy]

	def show; end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit; end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:notice] = 'Article has been created successfully'
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:notice] = 'Article was updated successfully'
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		flash[:notice] = 'Article was deleted successfully'
		redirect_to articles_path
	end

	private

	def article_params
		params.require(:article).permit(:title, :description, category_ids: [])
	end

	def set_article
		@article = Article.find(params[:id])
	end

	def require_same_user
		if current_user != @article.user && !current_user.admin?
			flash[:error] = 'You can only edit or delete your own articles'
			redirect_to @article
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: %i[index show]
	def index
		@categories = Category.paginate(page: params[:page], per_page: 3)
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
		@articles = @category.articles.paginate(page: params[:page], per_page: 3)
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to @category
			flash[:notice] = 'Category created successfully'
		else
			render :new
		end
	end

	def edit
	  @category = Category.find(params[:id])
  end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to @category
			flash[:notice] = 'Category updated successfully'
		else
			render :edit
		end
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || (logged_in? && !current_user.admin?)
			flash[:alert] = 'Only admins can perform that action'
			redirect_to categories_path
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def index
		@user = User.new
	end

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			flash[:notice] = "You have successfully logged in #{user.username}"
			session[:user_id] = user.id

			#sign_in user
			redirect_to user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = 'You have successfully logged out'
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, except: %i[index new create]
	before_action :require_user, only: %i[edit update destroy]
	before_action :require_same_user, only: %i[edit update destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to articles_path, notice: "Welcome to the site #{@user.username}"
		else
			render :new
		end
	end

	def show
		@articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def edit; end

	def update
		if @user.update(user_params)
			redirect_to @user, notice: 'Your account was updated successfully'
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil if @user == current_user
		redirect_to root_path, notice: 'Account and all associated articles successfully deleted'
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user && !current_user.admin?
			flash[:alert] = 'You can only edit or delete your own account'
			redirect_to @user
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80, class: 'gravatar' })
		email_address = user.email.downcase
		hash = Digest::MD5.hexdigest(email_address)
		size = options[:size]
		gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: options[:class])
	end
end

app/views/articles/_article.html.erb
<!--User articles-->

  <% @articles.each do |article| %>
  <div class="row d-flex justify-content-center mt-3 mb-3">
      <div class="col-lg-6">
        <div class="card">
            
            <div class="comment-widgets">
            
                <!-- Article Row -->
                <div class="d-flex flex-row comment-row mb-3 mb-3">
                    <div class="p-2"><%= gravatar_for(article.user, size: 100, class: "rounded-circle") %></div>
                    <div class="comment-text w-3">
                        <h6 class="font-medium mt-3">By <%= article.user.username if article.user %></h6>

                        <% if article.categories.any? %>
                          <%= render article.categories %>
                        <% end %>
                        
                        <span class="m-b-15 d-block text-success"><%= article.title %></span>
                        <p class="text-muted"><%= article.description %> </p>
                        <p class="text-muted">Created: <%= time_ago_in_words(article.created_at) %> ago Edited: <%= time_ago_in_words(article.updated_at) %> ago</p>
                        <div class="comment-footer"></span> 
                          <%= link_to "View", article, :class => 'btn btn-primary btn-sm' %>
                          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                            <%= link_to "Edit", edit_article_path(article), :class => "btn btn-secondary btn-sm" %>
                            <%= link_to 'Delete', article_path(article), :class => 'btn btn-danger btn-sm', method: :delete, data: {confirm: "Delete this article?"} %>
                          <% end %>
                        </div>
                    </div>
                </div> 
                <!--End Article Row -->
            
                 
            </div> <!-- Card -->
        </div>
      </div>
  </div>
  <% end %>
  
  <!--End user articles-->

app/views/articles/_form.html.erb
<%= render 'layouts/errors', obj: @article %>


<div class="form">
  <div class="form-group">
    <%= form_with(model: @article, local: true) do |form| %>
      <div class="field">
        <%= form.label :title %> <br/>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :description %><br/>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :categories %>
        <%= form.collection_select(
         :category_ids,
         Category.all,
         :id,
         :name,
         { prompt: "Select a category"},
         { multiple: true, class: "form-select shadow rounded mb-3", size: Category.all.count + 1 }) 
        %>
      </div>

      <div class="actions">
        <%= form.submit :class => 'btn btn-primary' %>
        <%= link_to 'Cancel', articles_path, class: "btn btn-secondary" %>
      </div>
      <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1 class="m-3 text-center">Showing Articles</h1>

<div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>
  
 <%= render 'article' %>

 <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= link_to 'New Article', new_article_path, :class => 'btn btn-primary' %>
  <%= link_to 'Sign Up', signup_path, :class => 'btn btn-primary' %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="text-center">New Article</h1>

  <%= render 'form' %>
  
  
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1 class="text-center m-3"> Showing Articles </h1>
  <div class="card">
            
            <div class="comment-widgets">
            
                <!-- Article Row -->
                <div class="d-flex flex-row comment-row mb-3 mb-3">
                    <div class="p-2"><%= gravatar_for(@article.user, size: 100, class: "rounded-circle") %></div>
                    <div class="comment-text w-3">
                        <h6 class="font-medium mt-3">By <%= @article.user.username if @article.user %></h6>

                        <% if @article.categories.any? %>
                          <%= render @article.categories %>
                        <% end %>
                        
                        <span class="m-b-15 d-block text-success"><%= @article.title %></span>
                        <p class="text-muted"><%= @article.description %> </p>
                        <p class="text-muted">Created: <%= time_ago_in_words(@article.created_at) %> ago Edited: <%= time_ago_in_words(@article.updated_at) %> ago</p>
                        <div class="comment-footer"></span> 
                          <%= link_to "Back to articles listing", articles_path, :class => 'btn btn-primary btn-sm' %>
                          <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                            <%= link_to "Edit", edit_article_path(@article), :class => "btn btn-secondary btn-sm" %>
                            <%= link_to 'Delete', article_path(@article), :class => 'btn btn-danger btn-sm', method: :delete, data: {confirm: "Delete this article?"} %>
                          <% end %>
                        </div>
                    </div>
                </div> 
                <!--End Article Row -->
            
                 
            </div> <!-- Card -->
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), :class => 'badge rounded-pill bg-info me-3 text-decoration-none' %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container">
    <h1 class="text-center mt-4">Listing categories</h1>

    <div class="flickr_pagination">
      <div class="page_info">
        <%= page_entries_info @categories %>
      </div>
      <%= will_paginate @categories, :container => false %>
    </div>

      <% @categories.each do |category| %>

        <div class="row justify-content-center">
          <div class="card mb-3 col-6">
                <div class="card-body">
                  <h5 class="card-title text-center"><%= link_to category.name, category_path(category), class: 'text-decoration-none link-success' %></h5>
                  <H5 class="text-center text-dark"><%= pluralize(category.articles.count, 'article') %></H5>
                </div>
                <div class="card-footer text-muted">
                  <small>
                    Created: <%= time_ago_in_words(category.created_at) %> ago.
                    Edited: <%= time_ago_in_words(category.updated_at) %> ago.
                  </small>
                </div>
          </div>
        </div>

      <% end %>

    <div class="flickr_pagination">
      <div class="page_info">
        <%= page_entries_info @categories %>
      </div>
      <%= will_paginate @categories, :container => false %>
    </div>

</div>

app/views/categories/new.html.erb
<h1> New Category </h1>
<%= render 'layouts/errors', obj: @category %>
<%= render 'form' %>

app/views/categories/show.html.erb
<h3 class="text-center">Category: <%= @category.name %></h3>

<% if  logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to 'Edit category name', edit_category_path(@category), :class => 'btn btn-primary' %>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'articles/article' %>

  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show">  
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if name == 'notice' %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <%= msg %>
        </div>
    <% elsif name == 'alert' %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <%= msg %>
        </div>
      <% elsif name == 'error' %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Alpha Bloggers", root_url, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, :class => "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <li>
                <%= link_to "Create new article", new_article_path, :class => "dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
            <% end %>
            <li>
              <%= link_to "View articles", articles_path, :class => "dropdown-item" %>
            </li>

          </ul>
        </li>

          <%# Categories DropDown %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin? %>
              <li>
                <%= link_to "Create new Category", new_category_path, :class => "dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
            <% end %>
            <li>
              <%= link_to "View Categories", categories_path, :class => "dropdown-item" %>
            </li>

          </ul>
        </li> <%# End Categories DropDown %>

        <li class="nav-item dropdown">
          <% if logged_in? %>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            
                <li>
                  <%= link_to "View Profile", user_path(current_user), :class => "dropdown-item" %>
                </li>

                <li><hr class="dropdown-divider"></li>

                <li>
                  <%= link_to "Edit Profile", edit_user_path(current_user), :class => "dropdown-item" %>
                </li>

                <li><hr class="dropdown-divider"></li>

                <li class="nav-item">
                  <%= link_to "Delete my account", user_path(current_user), method: :delete, data: { confirm: "Your account and all asociated articles will be destroyed, Are you sure?" }, :class => "dropdown-item" %>
                </li>

              </ul>

              <li class="nav-item">
                <%= link_to "Logout", logout_path, method: :delete, data: { confirm: "Do want to leave?" }, :class => "nav-link" %>
              </li>

          <% else %>
                
                <li><hr class="dropdown-divider"></li>

                <li>
                  <%= link_to "Login", login_path, :class => "nav-link" %>
                </li>

                <li>
                  <%= link_to "Signup", signup_path, :class => "nav-link" %>
                </li>
              
          <% end %>
            
            
        </li>
        

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= render 'layouts/errors', obj: @user %>

<%= form_with(model: @user, local: true, html: {class: 'shadow p-3 mb-3 bg-info rounded'}) do |f| %>
  <div class="field">
    <%= f.label :username %> <br/>
    <%= f.text_field :username, :placeholder => 'Enter an username', :class => 'form-control shadow rounded' %>
  </div>

  <div class="field">
    <%= f.label :email %> <br/>
    <%= f.email_field :email, :placeholder => 'Enter your email', :class => 'form-control shadow rounded' %>
  </div>

  <div class="field">
    <%= f.label :password %> <br/>
    <%= f.password_field :password, :placeholder => 'Enter your password', :class => 'form-control shadow rounded' %>
  </div>

  <div class="actions mt-4">
    <%= f.submit :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', articles_path, :class => 'btn btn-secondary' %>
  </div>
<% end %>

<div class="container">
<%= link_to 'Back to articles listing', articles_path, :class => 'btn btn-secondary' %>
</div>

app/views/users/_user.html.erb
<div class="container mt-5">
    <div class="card profile-header">
        <div class="body mt-3">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-12">
                    <div class="profile-image float-md-right"> <%= gravatar_for(user, size: 100, class: "rounded-circle m-3") %> </div>
                </div>
                <div class="col-lg-8 col-md-8 col-12">
                    <h4 class="m-t-0 m-b-0"><strong><%= user.username %></strong></h4>


                    <span class="job_post"><%= user.email %></span>
                    <p><%= pluralize(user.articles.count, "articles") %></p>
                    <div class="mb-3">
                        <%= link_to "View Profile", user_path(user), class: "btn btn-primary btn-round" %>
                        <% if logged_in? %>
                          <% if current_user == user %>
                            <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-primary btn-round btn-simple" %>
                          <% end %>
                          <% if current_user.admin? %>
                            <%= link_to "Delete Profile", user_path(user), method: :delete, data: { confirm: "Your account and all asociated articles will be destroyed, Are you sure?" }, class: "btn btn-danger btn-round btn-simple" %>
                          <% end %>
                        <% end %>
                    </div>
                </div>                
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1> Edit user profile </h1>
<%= render :partial => 'form', :locals => { :user => @user } %>

app/views/users/index.html.erb
<div class="container">

  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
  </div>

  <% @users.each do |user| %>
    <%= render partial: 'user', locals: { user: user } %>
  <% end %>

  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
  </div>
  
</div>

app/views/users/new.html.erb
<h1 class='text-center mt-4'>Sign Up</h1>
<% if @user.errors.any? %>
  <h2>The following errors prevented the <%= @user.class.name.downcase %> from being saved</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="section">
  <div class="container">
    <div class="row full-height justify-content-center">
      <div class="col-12 text-center align-self-center py-5">
        <div class="section pb-5 pt-5 pt-sm-2 text-center">
          <h6 class="mb-0 pb-3"><span>Log In </span><span>Sign Up</span></h6>
                <input class="checkbox" type="checkbox" id="reg-log" name="reg-log"/>
                <label for="reg-log"></label>
          <div class="card-3d-wrap mx-auto">
            <div class="card-3d-wrapper">

                  <div class="card-front">
                    <div class="center-wrap">
                      <div class="section text-center">
                        <h4 class="mb-4 pb-3">Log In</h4>
                    <%= form_with(scope: :session, url: login_path, local: true) do |f| %>
                        <div class="form-group">
                          <%= f.email_field :email, :placeholder => 'Your Email', :class => 'form-style', :id => 'logemail' %>
                          <i class="input-icon uil uil-at"></i>
                        </div>	
                        <div class="form-group mt-2">
                          <%= f.password_field :password, :placeholder => 'Your Password', :class => 'form-style', :id => 'logpass', :autocomplete => 'off' %>
                          <i class="input-icon uil uil-lock-alt"></i>
                        </div>
                        <%= f.submit :class => 'btn mt-4' %>
                    <% end %>
                      </div>
                    </div>
                  </div>
                
                  <div class="card-back">
                    <div class="center-wrap">
                      <div class="section text-center">
                        <h4 class="mb-4 pb-3">Sign Up</h4>
                      <%= form_with(model: @user, local: true) do |f| %>
                        <div class="form-group">
                          <%= f.text_field :username, :placeholder => 'Your Username', :class => 'form-style' %>
                          <i class="input-icon uil uil-user"></i>
                        </div>	
                        <div class="form-group mt-2">
                          <%= f.email_field :email, :placeholder => 'Your Email', :class => 'form-style' %>
                          <i class="input-icon uil uil-at"></i>
                        </div>	
                        <div class="form-group mt-2">
                          <%= f.password_field :password, :placeholder => 'Select a Password', :class => 'form-style', :autocomplete => 'off' %>
                          <i class="input-icon uil uil-lock-alt"></i>
                        </div>
                        <%= f.submit :class => 'btn mt-4' %>
                      <% end %>
                      </div>
                    </div>
                  </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
 

app/views/users/show.html.erb
 <div class="container mt-5">
    <h1 class="text-center">User Profile</h1>
    <div class="row d-flex justify-content-center mb-3">
        <div class="col-md-7">
            <div class="card p-3 py-4">
                <div class="text-center"> <%= gravatar_for(@user, size: 100, class: "rounded-circle m-3") %> </div>
                <div class="text-center mt-3">
                  <% if logged_in? && (current_user == @user) %>
                    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-small btn-primary" %>
                    <%= link_to "Delete Profile", user_path(@user), method: :delete, data: { confirm: "Your account and all asociated articles will be destroyed, Are you sure?" }, class: "btn btn-small btn-danger" %>
                  <% end %>
                    <h5 class="mt-2 mb-0"><%= @user.username %></h5>
                    <h5 class="mt-2 mb-0">Latest Articles</h5>
                </div>
            </div>
        </div>
    </div>
  
  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/article' %>

</div>